Task2
Pavlova-Alena-student/2022-MathMech-f-sharp-lessons pull request #3
Opened 2022-10-20 20:51 UTC by Pavlova-Alena-student

Написала оба варианта листа, добавила тесты. Документацию не умею писать.

Надеюсь на много-много правок :)

2022-10-20 20:55 UTC, Pavlova-Alena-student commented
А почему оно пишет, что у него SDK не тот? `read ECONNRESET`? Что я сломала? Как починить?

2022-10-21 05:22 UTC, gsvgit commented on src/2022MathMechFSharpLessons/FuncList.fs
> +    let rec ConCat a b =
Хорошая игра с кейсом)

2022-10-21 05:22 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/FuncListTests.fs
> +        testList
Подумайте, как добавить тетсты свойств. У Вас даже свойство хорошее есть: ```IsSorted```.

2022-10-21 05:22 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/Task2Tests.fs
> +open _2022MathMechFSharpLessons
Пространства имён лучше так не называть. С подчёрка.

2022-10-21 05:23 UTC, gsvgit commented
> А почему оно пишет, что у него SDK не тот? `read ECONNRESET`? Что я сломала? Как починить?

Видимо был локальный сбой на серваке. Я перезапустил одну из упавших тасок и она отработала. Бывает такое.

2022-10-21 13:16 UTC, Pavlova-Alena-student commented on src/2022MathMechFSharpLessons/FuncList.fs
> +    let rec ConCat a b =
?

2022-10-21 13:17 UTC, Pavlova-Alena-student commented on tests/2022MathMechFSharpLessons.Tests/FuncListTests.fs
> +        testList
Придумала свойство: длина списка должна быть такой же как и у исходного списка
На другие свойства воображения не хватает...

2022-10-21 13:18 UTC, Pavlova-Alena-student commented on tests/2022MathMechFSharpLessons.Tests/Task2Tests.fs
> +open _2022MathMechFSharpLessons
done

2022-10-24 05:54 UTC, gsvgit requested changes
Разберитесь с тестированием свойств. В остальном вполне прилично.

2022-10-24 05:54 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/OOPListTests.fs
> +    let rec IsSorted cmp (lst: IList<'value>) =
IsSorted вижу. Тестирования свойств не вижу. Если что, я вот про это: https://github.com/haf/expecto#property-based-tests

2022-10-24 05:54 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/Task2Tests.fs
> +    let tests =
Вот тут точно свойства нормально надо делать.

2022-11-16 04:18 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/FuncListTests.fs
> +              testProperty "Comparing functional qsort test (prop)"
Из очевидного.
1. Пакет нужный установили?
2. Наверняка нужно открыть какое-нибудь пространство имён.

2022-11-16 04:18 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/FuncListTests.fs
> +              testProperty "Comparing functional qsort test (prop)"
Из очевидного.
1. Пакет нужный установили?
2. Наверняка нужно открыть какое-нибудь пространство имён.

2023-01-30 08:06 UTC, gsvgit requested changes

2023-01-30 08:06 UTC, gsvgit commented on src/2022MathMechFSharpLessons/FuncList.fs
> +    let rec GenerateList rGenerator length =
Бу. Зачем такое злодейство? Пусть лучше прямой порядок нумерации будет.

2023-01-30 08:06 UTC, gsvgit commented on src/2022MathMechFSharpLessons/FuncList.fs
> +    let rec ConCat a b =
Ну, мне казалось, что конкатенация, она не от котов.

2023-01-30 08:06 UTC, gsvgit commented on src/2022MathMechFSharpLessons/FuncList.fs
> +    let QuickSort cmp a =
Лучше сразу lst или l хотя бы.

2023-01-30 08:06 UTC, gsvgit commented on src/2022MathMechFSharpLessons/Task2.fs
> +module Task2 =
Лучше посмотриет где в стандартной библиотеке живут конвертеры между коллекциями.

2023-01-30 08:06 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/FuncListTests.fs
> +                  let b = a
А вот это зачем?

2023-01-30 08:06 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/FuncListTests.fs
> +                  let b = a
Зачем?

2023-02-20 06:09 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/FuncListTests.fs
> +                  let subject = Concat a Empty
Не надо всё в одну кучу мешать.

2023-02-20 06:09 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/FuncListTests.fs
> +                  let subjectIS = InsertionSort(<) a
Не надо всё в одну кучу мешать.

2023-02-20 06:09 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/FuncListTests.fs
> +                  let b = a
Таки зачем?

2023-02-20 06:09 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/FuncListTests.fs
> +                  let subject = BubbleSort(>) b
И снова всё в кучу.

2023-02-22 14:44 UTC, gsvgit commented on src/2022MathMechFSharpLessons/Task2.fs
> +namespace MathMechFSharpLessons
А это что, просто пустой файл что ли?

2023-02-22 14:47 UTC, gsvgit approved these changes

2023-02-23 08:43 UTC, Pavlova-Alena-student commented on src/2022MathMechFSharpLessons/Task2.fs
> +namespace MathMechFSharpLessons
Угу

2023-02-23 08:44 UTC, merged