Task4
Pavlova-Alena-student/2022-MathMech-f-sharp-lessons pull request #5
Opened 2023-04-09 20:10 UTC by Pavlova-Alena-student

## Proposed Changes

Это 4 домашнее задание 1 семестра :)
13.04 будет комиссия

## Checklist

- [X] Типы вектор и матрица есть, умножение есть
- [X] В README есть описание
- [X] Тесты написала; кажется, они проходят

2023-04-10 06:26 UTC, gsvgit requested changes

2023-04-10 06:26 UTC, gsvgit commented on src/2022MathMechFSharpLessons/Utils.fs
> +    let flip f b a = f a b // could not find this function among standart ones
На всякий случай: https://fsprojects.github.io/FSharpx.Extras/reference/fsharpx-functional-prelude.html

2023-04-10 06:26 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/LinAlgTests.fs
> +                    <| fun _ ->
Не надо пачку тестов скливать в один.

2023-04-10 06:26 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/LinAlgTests.fs
> +                    testProperty "Multiplication of vectors to matrixes (prop)"
А можно ли на каких-то более содержательных случайных матрицах и векторах протестировать?

2023-04-10 15:15 UTC, Pavlova-Alena-student commented on src/2022MathMechFSharpLessons/Utils.fs
> +    let flip f b a = f a b // could not find this function among standart ones
Спасибо!

2023-04-10 15:15 UTC, Pavlova-Alena-student commented on tests/2022MathMechFSharpLessons.Tests/LinAlgTests.fs
> +                    <| fun _ ->
Да...

2023-04-10 15:16 UTC, Pavlova-Alena-student commented on tests/2022MathMechFSharpLessons.Tests/LinAlgTests.fs
> +                    testProperty "Multiplication of vectors to matrixes (prop)"
Я не знаю что на них проверять... Могу проверять, что произведение падает, если размеры не сходятся

2023-04-10 15:25 UTC, gsvgit commented on tests/2022MathMechFSharpLessons.Tests/LinAlgTests.fs
> +                    testProperty "Multiplication of vectors to matrixes (prop)"
Проверять можно, что Ваша хитрая реализация работает точно как наивная.

2023-04-12 17:50 UTC, gsvgit approved these changes
Пойдет.

2023-04-12 17:59 UTC, merged